name: Build Types

on: 
  workflow_dispatch:
    inputs:
      version:
        description: "Version number"

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  cratesio:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose --release
      - name: Publish to crates.io
        run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }} --allow-dirty